version: '3'
services:

    #### Monitoring front-end ####
    prometheus:
        build: prometheus/
        ports:
            - 8888:9090
        volumes:
            - prometheus_data:/prometheus
            - ./charts_html:/usr/share/prometheus/consoles

    #### runZoo ####
    zooKeeper:
        image: quay.io/miratepuffin/zookeeper:latest
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888

    #### seedSetup ####
    seedNode:
       image: miratepuffin/raphtory
       depends_on: 
            - zooKeeper
       ports:
            - 9101:9101
       command: env-setter.sh seedNode
       environment:
            - BIND_PORT=9101
            - HOST_PORT=9101
            - ZOOKEEPER=$ZOOKEEPER

#    rest:
#       image: miratepuffin/raphtory
#       depends_on: 
#            - seedNode
#       ports:
#            - 8080:8080
#       command: rest $ZOOKEEPER
#       environment:
#            - BIND_PORT=9101
#            - HOST_PORT=9101
#            - HOST_IP=raphtory_rest_1
#    benchmarker:
#        image: miratepuffin/raphtory
#        depends_on: 
#            - seedNode
#        ports: 
#            - 9104:9104
#        command: benchmark $NUMBER_OF_PARTITIONS $ZOOKEEPER
#        environment:
#            # Are both the variables used?
#            - BIND_PORT=9104
#            - HOST_PORT=9105
#            - HOST_IP=raphtory_benchmarker_1

    #### Machines Setup ####
    partitionManager:
        image: miratepuffin/raphtory
        depends_on: 
            - seedNode
        ports:
            - 9200:9200
        command: env-setter.sh partitionManager
        environment:
            - BIND_PORT=9200
            - HOST_PORT=9200
            - ZOOKEEPER=$ZOOKEEPER
            - NUMBER_OF_PARTITIONS=$NUMBER_OF_PARTITIONS
        deploy:
            replicas: 1
            update_config:
                delay: "0"
            restart_policy:
                condition: on-failure

    router:
        image: miratepuffin/raphtory
        depends_on: 
            - partitionManager
        ports:
            - 9300:9300
        command: env-setter.sh router
        environment:
            - BIND_PORT=9300
            - HOST_PORT=9300
            - ZOOKEEPER=$ZOOKEEPER
            - NUMBER_OF_PARTITIONS=$NUMBER_OF_PARTITIONS
        deploy:
            replicas: 1
            update_config:
                delay: "0"
            restart_policy:
                condition: on-failure

    updater:
        image: miratepuffin/raphtory
        depends_on: 
            - router
        ports:
            - 9400:9400
        command: env-setter.sh updater
        environment:
            - BIND_PORT=9400
            - HOST_PORT=9400
            - HOST_IP=raphtory_updater_1
            - NUMBER_OF_PARTITIONS=$NUMBER_OF_PARTITIONS
            - ZOOKEEPER=$ZOOKEEPER
        deploy:
            replicas: 1
            update_config:
                delay: "0"
            restart_policy:
                condition: on-failure
#
#    clusterUp:
#        image: miratepuffin/raphtory
#        depends_on: 
#            - updater
#        ports:
#            - 9106:9106
#        command: env-setter.sh clusterUp
#        environment:
#            - BIND_PORT=9106
#            - HOST_PORT=9106
#            - NUMBER_OF_PARTITIONS=$NUMBER_OF_PARTITIONS
#            - ZOOKEEPER=$ZOOKEEPER
#
#        deploy:
#            replicas: 1
#            update_config:
#                 delay: "0"
#            restart_policy:
#                condition: on-failure

#    lam:
#        image: miratepuffin/raphtory
#        depends_on: 
#            - clusterUp
#        ports:
#            - 9105:9105
#        command: LiveAnalysisManager $NUMBER_OF_PARTITIONS $ZOOKEEPER $LAM_NAME
#        environment:
#            - BIND_PORT=9105
#            - HOST_PORT=9105
#            - HOST_IP=raphtory_lam_1

volumes:
    prometheus_data:
